const shuffledList = [
    "Benin",
    "South Korea",
    "Austria",
    "Egypt",
    "Bosnia and Herzegovina",
    "Croatia",
    "Chad",
    "Estonia",
    "Burkina Faso",
    "Jamaica",
    "Cuba",
    "Ghana",
    "Finland",
    "Ethiopia",
    "Ecuador",
    "Australia",
    "France",
    "Congo",
    "Greece",
    "Algeria",
    "Belgium",
    "Haiti",
    "China",
    "Iceland",
    "Armenia",
    "Ireland",
    "Cameroon",
    "Czechia",
    "Kazakhstan",
    "Canada",
    "Japan",
    "Italy",
    "Iran",
    "India",
    "Afghanistan",
    "Lebanon",
    "Kuwait",
    "Hungary",
    "Albania",
    "Belize",
    "Latvia",
    "Dominican Republic",
    "Kyrgyzstan",
    "Angola",
    "Chile",
    "Costa Rica",
    "El Salvador",
    "Greenland",
    "Denmark",
    "Côte d'Ivoire",
    "Belarus",
    "Colombia",
    "Libya",
    "Botswana",
    "Gabon",
    "Germany",
    "Bhutan",
    "Bangladesh",
    "Jordan",
    "Cambodia",
    "Djibouti",
    "Brazil",
    "Kenya",
    "Eritrea",
    "Argentina",
    "Guatemala",
    "Honduras",
    "Israel",
    "Bolivia",
    "Central African Republic",
    "Iraq",
    "Indonesia",
    "Eswatini",
    "Bulgaria",
    "Palestine",
    "Nepal",
    "Zimbabwe",
    "Tunisia",
    "Norway",
    "Madagascar",
    "Netherlands",
    "Mongolia",
    "Paraguay",
    "Saudi Arabia",
    "Uruguay",
    "Venezuela",
    "Slovakia",
    "United States of America",
    "Mali",
    "Senegal",
    "Poland",
    "Malaysia",
    "South Africa",
    "Pakistan",
    "Turkey",
    "Sudan",
    "Sweden",
    "Mauritania",
    "Turkmenistan",
    "Serbia",
    "Somalia",
    "Malta",
    "Uganda",
    "Tanzania",
    "Vietnam",
    "Romania",
    "Moldova",
    "Lithuania",
    "Ukraine",
    "Yemen",
    "Russia",
    "Philippines",
    "Luxembourg",
    "Montenegro",
    "Slovenia",
    "Myanmar",
    "Panama",
    "Monaco",
    "Portugal",
    "Peru",
    "United Arab Emirates",
    "Togo",
    "Sri Lanka",
    "United Kingdom",
    "Morocco",
    "Oman",
    "Nicaragua",
    "Syria",
    "Nigeria",
    "Thailand",
    "Qatar",
    "Mexico",
    "Spain",
    "Rwanda",
    "South Sudan",
    "Puerto Rico",
    "New Zealand",
    "Switzerland",
    "Singapore",
    "Mozambique",
];

export default shuffledList;